name: reich-backend
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - ipykernel
  - nextflow
  - python>=3.6
  - r-base
  - r-tidyverse
  - fastp
  - bowtie2
  - minimap2
  - seqtk
  - samtools
  - taxonkit
  - pigz
  - pip
  - pip:
    - black
    - click
    - click-option-group
    - flask
